package com.hendisantika.dynamicmultitenancy.tenant.entity;
// Generated 23 avr. 2022, 13:09:37 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Currencies generated by hbm2java
 */
@Entity
@Table(name = "currencies")
public class Currencies implements java.io.Serializable {

	private Long    id;
	private String code;
	private String name;
	private String symbol;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;


	public Currencies() {
	}

	public Currencies(Long    id, String code, String name, String symbol) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.symbol = symbol;
	}

	public Currencies(Long    id, String code, String name, String symbol, Date createdAt, Date updatedAt, Date deletedAt) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.symbol = symbol;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;

	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long    getId() {
		return this.id;
	}

	public void setId(Long     id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 192)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 192)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "symbol", nullable = false, length = 192)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	
}
