package com.hendisantika.dynamicmultitenancy.tenant.entity;
// Generated 23 avr. 2022, 13:09:37 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Servers generated by hbm2java
 */
@Entity
@Table(name = "servers")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Servers implements java.io.Serializable {

	private Long id;
	private String host;
	private Long port;
	private String username;
	private String password;
	private String encryption;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
/*
	public Servers() {
	}
*/
	public Servers(Long id, String host, Long port, String username, String password, String encryption) {
		this.id = id;
		this.host = host;
		this.port = port;
		this.username = username;
		this.password = password;
		this.encryption = encryption;
	}
/*
	public Servers(Long id, String host, Long port, String username, String password, String encryption, Date createdAt,
			Date updatedAt, Date deletedAt) {
		this.id = id;
		this.host = host;
		this.port = port;
		this.username = username;
		this.password = password;
		this.encryption = encryption;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
	}
*/
	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "host", nullable = false, length = 191)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "port", nullable = false)
	public Long getPort() {
		return this.port;
	}

	public void setPort(Long port) {
		this.port = port;
	}

	@Column(name = "username", nullable = false, length = 191)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 191)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "encryption", nullable = false, length = 191)
	public String getEncryption() {
		return this.encryption;
	}

	public void setEncryption(String encryption) {
		this.encryption = encryption;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

}
