package com.hendisantika.dynamicmultitenancy.tenant.entity;
// Generated 23 avr. 2022, 13:09:37 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Units generated by hbm2java
 */
@Entity
@Table(name = "units")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Units implements java.io.Serializable {

	private Long id;
	private Units units;
	private String name;
	private String shortname;
	private String operator;
	private Double operatorValue;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set<Products> productsesForUnitPurchaseId = new HashSet<Products>(0);
	private Set<PurchaseDetails> purchaseDetailses = new HashSet<PurchaseDetails>(0);
	private Set<QuotationDetails> quotationDetailses = new HashSet<QuotationDetails>(0);
	private Set<Products> productsesForUnitSaleId = new HashSet<Products>(0);
	private Set<SaleDetails> saleDetailses = new HashSet<SaleDetails>(0);
	private Set<PurchaseReturnDetails> purchaseReturnDetailses = new HashSet<PurchaseReturnDetails>(0);
	private Set<Products> productsesForUnitId = new HashSet<Products>(0);
	private Set<SaleReturnDetails> saleReturnDetailses = new HashSet<SaleReturnDetails>(0);
	private Set<TransferDetails> transferDetailses = new HashSet<TransferDetails>(0);
	private Set<Units> unitses = new HashSet<Units>(0);

	/*public Units() {
	}
*/
	public Units(Long id, String name, String shortname) {
		this.id = id;
		this.name = name;
		this.shortname = shortname;
	}
/*
	public Units(Long id, Units units, String name, String shortname, String operator, Double operatorValue,
			Date createdAt, Date updatedAt, Date deletedAt, Set<Products> productsesForUnitPurchaseId,
			Set<PurchaseDetails> purchaseDetailses, Set<QuotationDetails> quotationDetailses,
			Set<Products> productsesForUnitSaleId, Set<SaleDetails> saleDetailses,
			Set<PurchaseReturnDetails> purchaseReturnDetailses, Set<Products> productsesForUnitId,
			Set<SaleReturnDetails> saleReturnDetailses, Set<TransferDetails> transferDetailses, Set<Units> unitses) {
		this.id = id;
		this.units = units;
		this.name = name;
		this.shortname = shortname;
		this.operator = operator;
		this.operatorValue = operatorValue;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.productsesForUnitPurchaseId = productsesForUnitPurchaseId;
		this.purchaseDetailses = purchaseDetailses;
		this.quotationDetailses = quotationDetailses;
		this.productsesForUnitSaleId = productsesForUnitSaleId;
		this.saleDetailses = saleDetailses;
		this.purchaseReturnDetailses = purchaseReturnDetailses;
		this.productsesForUnitId = productsesForUnitId;
		this.saleReturnDetailses = saleReturnDetailses;
		this.transferDetailses = transferDetailses;
		this.unitses = unitses;
	}
*/
	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "base_unit")
	public Units getUnits() {
		return this.units;
	}

	public void setUnits(Units units) {
		this.units = units;
	}

	@Column(name = "name", nullable = false, length = 192)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "shortname", nullable = false, length = 192)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@Column(name = "operator", length = 192)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "operator_value", precision = 17, scale = 17)
	public Double getOperatorValue() {
		return this.operatorValue;
	}

	public void setOperatorValue(Double operatorValue) {
		this.operatorValue = operatorValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitsByUnitPurchaseId")
	public Set<Products> getProductsesForUnitPurchaseId() {
		return this.productsesForUnitPurchaseId;
	}

	public void setProductsesForUnitPurchaseId(Set<Products> productsesForUnitPurchaseId) {
		this.productsesForUnitPurchaseId = productsesForUnitPurchaseId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "units")
	public Set<PurchaseDetails> getPurchaseDetailses() {
		return this.purchaseDetailses;
	}

	public void setPurchaseDetailses(Set<PurchaseDetails> purchaseDetailses) {
		this.purchaseDetailses = purchaseDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "units")
	public Set<QuotationDetails> getQuotationDetailses() {
		return this.quotationDetailses;
	}

	public void setQuotationDetailses(Set<QuotationDetails> quotationDetailses) {
		this.quotationDetailses = quotationDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitsByUnitSaleId")
	public Set<Products> getProductsesForUnitSaleId() {
		return this.productsesForUnitSaleId;
	}

	public void setProductsesForUnitSaleId(Set<Products> productsesForUnitSaleId) {
		this.productsesForUnitSaleId = productsesForUnitSaleId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "units")
	public Set<SaleDetails> getSaleDetailses() {
		return this.saleDetailses;
	}

	public void setSaleDetailses(Set<SaleDetails> saleDetailses) {
		this.saleDetailses = saleDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "units")
	public Set<PurchaseReturnDetails> getPurchaseReturnDetailses() {
		return this.purchaseReturnDetailses;
	}

	public void setPurchaseReturnDetailses(Set<PurchaseReturnDetails> purchaseReturnDetailses) {
		this.purchaseReturnDetailses = purchaseReturnDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitsByUnitId")
	public Set<Products> getProductsesForUnitId() {
		return this.productsesForUnitId;
	}

	public void setProductsesForUnitId(Set<Products> productsesForUnitId) {
		this.productsesForUnitId = productsesForUnitId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "units")
	public Set<SaleReturnDetails> getSaleReturnDetailses() {
		return this.saleReturnDetailses;
	}

	public void setSaleReturnDetailses(Set<SaleReturnDetails> saleReturnDetailses) {
		this.saleReturnDetailses = saleReturnDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "units")
	public Set<TransferDetails> getTransferDetailses() {
		return this.transferDetailses;
	}

	public void setTransferDetailses(Set<TransferDetails> transferDetailses) {
		this.transferDetailses = transferDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "units")
	public Set<Units> getUnitses() {
		return this.unitses;
	}

	public void setUnitses(Set<Units> unitses) {
		this.unitses = unitses;
	}

}
