package com.hendisantika.dynamicmultitenancy.tenant.entity;
// Generated 23 avr. 2022, 13:09:37 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Warehouses generated by hbm2java
 */
@Entity
@Table(name = "warehouses")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Warehouses implements java.io.Serializable {

	private int id;
	private String name;
	private String city;
	private String mobile;
	private String zip;
	private String email;
	private String country;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set<ProductWarehouse> productWarehouses = new HashSet<ProductWarehouse>(0);
	private Set<Quotations> quotationses = new HashSet<Quotations>(0);
	private Set<SaleReturns> saleReturnses = new HashSet<SaleReturns>(0);
	private Set<Transfers> transfersesForFromWarehouseId = new HashSet<Transfers>(0);
	private Set<Transfers> transfersesForToWarehouseId = new HashSet<Transfers>(0);
	private Set<Purchases> purchaseses = new HashSet<Purchases>(0);
	private Set<Sales> saleses = new HashSet<Sales>(0);
	private Set<Settings> settingses = new HashSet<Settings>(0);
	private Set<Expenses> expenseses = new HashSet<Expenses>(0);
	private Set<PurchaseReturns> purchaseReturnses = new HashSet<PurchaseReturns>(0);
	private Set<Adjustments> adjustmentses = new HashSet<Adjustments>(0);
/*
	public Warehouses() {
	}
*/
	public Warehouses(int id, String name) {
		this.id = id;
		this.name = name;
	}

	/*public Warehouses(int id, String name, String city, String mobile, String zip, String email, String country,
			Date createdAt, Date updatedAt, Date deletedAt, Set<ProductWarehouse> productWarehouses,
			Set<Quotations> quotationses, Set<SaleReturns> saleReturnses, Set<Transfers> transfersesForFromWarehouseId,
			Set<Transfers> transfersesForToWarehouseId, Set<Purchases> purchaseses, Set<Sales> saleses,
			Set<Settings> settingses, Set<Expenses> expenseses, Set<PurchaseReturns> purchaseReturnses,
			Set<Adjustments> adjustmentses) {
		this.id = id;
		this.name = name;
		this.city = city;
		this.mobile = mobile;
		this.zip = zip;
		this.email = email;
		this.country = country;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.productWarehouses = productWarehouses;
		this.quotationses = quotationses;
		this.saleReturnses = saleReturnses;
		this.transfersesForFromWarehouseId = transfersesForFromWarehouseId;
		this.transfersesForToWarehouseId = transfersesForToWarehouseId;
		this.purchaseses = purchaseses;
		this.saleses = saleses;
		this.settingses = settingses;
		this.expenseses = expenseses;
		this.purchaseReturnses = purchaseReturnses;
		this.adjustmentses = adjustmentses;
	}
*/
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 192)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "city", length = 192)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "mobile", length = 192)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "zip", length = 192)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "email", length = 192)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "country", length = 192)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<ProductWarehouse> getProductWarehouses() {
		return this.productWarehouses;
	}

	public void setProductWarehouses(Set<ProductWarehouse> productWarehouses) {
		this.productWarehouses = productWarehouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<Quotations> getQuotationses() {
		return this.quotationses;
	}

	public void setQuotationses(Set<Quotations> quotationses) {
		this.quotationses = quotationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<SaleReturns> getSaleReturnses() {
		return this.saleReturnses;
	}

	public void setSaleReturnses(Set<SaleReturns> saleReturnses) {
		this.saleReturnses = saleReturnses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehousesByFromWarehouseId")
	public Set<Transfers> getTransfersesForFromWarehouseId() {
		return this.transfersesForFromWarehouseId;
	}

	public void setTransfersesForFromWarehouseId(Set<Transfers> transfersesForFromWarehouseId) {
		this.transfersesForFromWarehouseId = transfersesForFromWarehouseId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehousesByToWarehouseId")
	public Set<Transfers> getTransfersesForToWarehouseId() {
		return this.transfersesForToWarehouseId;
	}

	public void setTransfersesForToWarehouseId(Set<Transfers> transfersesForToWarehouseId) {
		this.transfersesForToWarehouseId = transfersesForToWarehouseId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<Purchases> getPurchaseses() {
		return this.purchaseses;
	}

	public void setPurchaseses(Set<Purchases> purchaseses) {
		this.purchaseses = purchaseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<Sales> getSaleses() {
		return this.saleses;
	}

	public void setSaleses(Set<Sales> saleses) {
		this.saleses = saleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<Settings> getSettingses() {
		return this.settingses;
	}

	public void setSettingses(Set<Settings> settingses) {
		this.settingses = settingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<Expenses> getExpenseses() {
		return this.expenseses;
	}

	public void setExpenseses(Set<Expenses> expenseses) {
		this.expenseses = expenseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<PurchaseReturns> getPurchaseReturnses() {
		return this.purchaseReturnses;
	}

	public void setPurchaseReturnses(Set<PurchaseReturns> purchaseReturnses) {
		this.purchaseReturnses = purchaseReturnses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouses")
	public Set<Adjustments> getAdjustmentses() {
		return this.adjustmentses;
	}

	public void setAdjustmentses(Set<Adjustments> adjustmentses) {
		this.adjustmentses = adjustmentses;
	}

}
